baseURL = "https://tumellop.github.io/"  # Your website URL
languageCode = "en"
title = "Tumello Phage"       # The title in the browser tab
theme = "LoveIt"            # The theme name (must match your folder name in 'themes')

[params]
  # default theme mode ("dark", "light", "auto")
  defaultTheme = "light"

  # Website Header Config
  [params.header]
    desktopMode = "fixed"
    mobileMode = "auto"

    [params.header.title]
      name = "prxncessZA"   
      pre = ""              
      typeit = true         

  # Home Page Config (The big profile section)
  [params.home]
    rss = 10
    [params.home.profile]
      enable = true
      gravatarEmail = ""
      avatarURL = "/images/avatar.jpeg"  
      title = "Tumello Phage"                        
      subtitle = "I am a blogger | coder | tech enthusiast" 
      typeit = true                     
      social = true                     

  # Social Media Links (Remove the ones you don't want)
  [params.social]
    GitHub = "tumellop"      
    Linkedin = "tumellop"   
    Instagram = "yourhandle"
    Email = "tumellop@gmail.com"

[menu]
  [[menu.main]]
    identifier = "about"
    pre = ""
    post = ""
    name = "About Me"
    url = "/about/"
    title = ""
    weight = 1

  [[menu.main]]
    identifier = "projects"
    pre = ""
    post = ""
    name = "Projects"
    url = "/projects/"
    title = ""
    weight = 2

  [[menu.main]]
    identifier = "posts"
    pre = ""
    post = ""
    name = "CTF Writeups"
    url = "/posts/"
    title = ""
    weight = 3

  [[menu.main]]
    identifier = "cv"        
    pre = ""
    post = ""
    name = "CV"              
    url = "/cv/"             
    title = ""
    weight = 4
 
  [[menu.main]]
    identifier = "contact"
    pre = ""
    post = ""
    name = "Contact"
    url = "/contact/"
    title = ""
    weight = 5 

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true    
